[package]
name = "sycamore-guestbook"
version = "0.1.0"
edition = "2021"

[dependencies]
sycamore = { version = "0.8.2", features = ["suspense"] }
supabase-js-rs = { path = "../../" }
web-sys = "0.3.60"
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"